name: demo-falopa

services:
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 3s
    environment:
      RABBITMQ_DEFAULT_LOG_LEVEL: error
      RABBITMQ_LOG_LEVELS: "connection=error"

  seeder:
    image: seeder:latest
    depends_on:
      rabbitmq:
        condition: service_healthy

  demo-falopa-1:
    image: workers:latest
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      ID: 1
    volumes:
      - ../database-falopa:/app/database
    restart: always

  # demo-falopa-2:
  #   image: workers:latest
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   environment:
  #     ID: 1

  # demo-falopa-3:
  #   image: workers:latest
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   environment:
  #     ID: 2
